/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as InscriptionSuccesImport } from './routes/inscription-succes'
import { Route as InscriptionImport } from './routes/inscription'
import { Route as ConnexionImport } from './routes/connexion'
import { Route as AdminImport } from './routes/admin'
import { Route as AProposImport } from './routes/a-propos'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as R403Import } from './routes/403'
import { Route as IndexImport } from './routes/index'
import { Route as ContactIndexImport } from './routes/contact/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as ActualitesIndexImport } from './routes/actualites/index'
import { Route as ContactMerciImport } from './routes/contact/merci'
import { Route as AdminUsersImport } from './routes/admin/users'
import { Route as AdminMagasinImport } from './routes/admin/magasin'
import { Route as AdminGlobalSettingsImport } from './routes/admin/global-settings'
import { Route as AdminCooperativesImport } from './routes/admin/cooperatives'
import { Route as AdminBlogImport } from './routes/admin/blog'
import { Route as AdminAnalyticsImport } from './routes/admin/analytics'
import { Route as ActualitesNewsIdImport } from './routes/actualites/$newsId'
import { Route as AuthenticatedProfilImport } from './routes/_authenticated/profil'
import { Route as AuthenticatedVentesNouvelleEnchereImport } from './routes/_authenticated/ventes/nouvelle-enchere'
import { Route as AuthenticatedVentesMesEncheresImport } from './routes/_authenticated/ventes/mes-encheres'
import { Route as AuthenticatedVentesEnchereCreeeImport } from './routes/_authenticated/ventes/enchere-creee'
import { Route as AuthenticatedDepotsNouveauProduitImport } from './routes/_authenticated/depots/nouveau-produit'
import { Route as AuthenticatedDepotsMesProduitsImport } from './routes/_authenticated/depots/mes-produits'
import { Route as AuthenticatedContratsMesContratsImport } from './routes/_authenticated/contrats/mes-contrats'
import { Route as AuthenticatedAchatsMesEncheresImport } from './routes/_authenticated/achats/mes-encheres'
import { Route as AuthenticatedAchatsMarcheImport } from './routes/_authenticated/achats/marche'

// Create/Update Routes

const InscriptionSuccesRoute = InscriptionSuccesImport.update({
  id: '/inscription-succes',
  path: '/inscription-succes',
  getParentRoute: () => rootRoute,
} as any)

const InscriptionRoute = InscriptionImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRoute,
} as any)

const ConnexionRoute = ConnexionImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRoute,
} as any)

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const AProposRoute = AProposImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const R403Route = R403Import.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ContactIndexRoute = ContactIndexImport.update({
  id: '/contact/',
  path: '/contact/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const ActualitesIndexRoute = ActualitesIndexImport.update({
  id: '/actualites/',
  path: '/actualites/',
  getParentRoute: () => rootRoute,
} as any)

const ContactMerciRoute = ContactMerciImport.update({
  id: '/contact/merci',
  path: '/contact/merci',
  getParentRoute: () => rootRoute,
} as any)

const AdminUsersRoute = AdminUsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)

const AdminMagasinRoute = AdminMagasinImport.update({
  id: '/magasin',
  path: '/magasin',
  getParentRoute: () => AdminRoute,
} as any)

const AdminGlobalSettingsRoute = AdminGlobalSettingsImport.update({
  id: '/global-settings',
  path: '/global-settings',
  getParentRoute: () => AdminRoute,
} as any)

const AdminCooperativesRoute = AdminCooperativesImport.update({
  id: '/cooperatives',
  path: '/cooperatives',
  getParentRoute: () => AdminRoute,
} as any)

const AdminBlogRoute = AdminBlogImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAnalyticsRoute = AdminAnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)

const ActualitesNewsIdRoute = ActualitesNewsIdImport.update({
  id: '/actualites/$newsId',
  path: '/actualites/$newsId',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedProfilRoute = AuthenticatedProfilImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedVentesNouvelleEnchereRoute =
  AuthenticatedVentesNouvelleEnchereImport.update({
    id: '/ventes/nouvelle-enchere',
    path: '/ventes/nouvelle-enchere',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedVentesMesEncheresRoute =
  AuthenticatedVentesMesEncheresImport.update({
    id: '/ventes/mes-encheres',
    path: '/ventes/mes-encheres',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedVentesEnchereCreeeRoute =
  AuthenticatedVentesEnchereCreeeImport.update({
    id: '/ventes/enchere-creee',
    path: '/ventes/enchere-creee',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDepotsNouveauProduitRoute =
  AuthenticatedDepotsNouveauProduitImport.update({
    id: '/depots/nouveau-produit',
    path: '/depots/nouveau-produit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedDepotsMesProduitsRoute =
  AuthenticatedDepotsMesProduitsImport.update({
    id: '/depots/mes-produits',
    path: '/depots/mes-produits',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedContratsMesContratsRoute =
  AuthenticatedContratsMesContratsImport.update({
    id: '/contrats/mes-contrats',
    path: '/contrats/mes-contrats',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAchatsMesEncheresRoute =
  AuthenticatedAchatsMesEncheresImport.update({
    id: '/achats/mes-encheres',
    path: '/achats/mes-encheres',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedAchatsMarcheRoute = AuthenticatedAchatsMarcheImport.update({
  id: '/achats/marche',
  path: '/achats/marche',
  getParentRoute: () => AuthenticatedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403Import
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionImport
      parentRoute: typeof rootRoute
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionImport
      parentRoute: typeof rootRoute
    }
    '/inscription-succes': {
      id: '/inscription-succes'
      path: '/inscription-succes'
      fullPath: '/inscription-succes'
      preLoaderRoute: typeof InscriptionSuccesImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/profil': {
      id: '/_authenticated/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof AuthenticatedProfilImport
      parentRoute: typeof AuthenticatedImport
    }
    '/actualites/$newsId': {
      id: '/actualites/$newsId'
      path: '/actualites/$newsId'
      fullPath: '/actualites/$newsId'
      preLoaderRoute: typeof ActualitesNewsIdImport
      parentRoute: typeof rootRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsImport
      parentRoute: typeof AdminImport
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogImport
      parentRoute: typeof AdminImport
    }
    '/admin/cooperatives': {
      id: '/admin/cooperatives'
      path: '/cooperatives'
      fullPath: '/admin/cooperatives'
      preLoaderRoute: typeof AdminCooperativesImport
      parentRoute: typeof AdminImport
    }
    '/admin/global-settings': {
      id: '/admin/global-settings'
      path: '/global-settings'
      fullPath: '/admin/global-settings'
      preLoaderRoute: typeof AdminGlobalSettingsImport
      parentRoute: typeof AdminImport
    }
    '/admin/magasin': {
      id: '/admin/magasin'
      path: '/magasin'
      fullPath: '/admin/magasin'
      preLoaderRoute: typeof AdminMagasinImport
      parentRoute: typeof AdminImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersImport
      parentRoute: typeof AdminImport
    }
    '/contact/merci': {
      id: '/contact/merci'
      path: '/contact/merci'
      fullPath: '/contact/merci'
      preLoaderRoute: typeof ContactMerciImport
      parentRoute: typeof rootRoute
    }
    '/actualites/': {
      id: '/actualites/'
      path: '/actualites'
      fullPath: '/actualites'
      preLoaderRoute: typeof ActualitesIndexImport
      parentRoute: typeof rootRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/contact/': {
      id: '/contact/'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactIndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/achats/marche': {
      id: '/_authenticated/achats/marche'
      path: '/achats/marche'
      fullPath: '/achats/marche'
      preLoaderRoute: typeof AuthenticatedAchatsMarcheImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/achats/mes-encheres': {
      id: '/_authenticated/achats/mes-encheres'
      path: '/achats/mes-encheres'
      fullPath: '/achats/mes-encheres'
      preLoaderRoute: typeof AuthenticatedAchatsMesEncheresImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/contrats/mes-contrats': {
      id: '/_authenticated/contrats/mes-contrats'
      path: '/contrats/mes-contrats'
      fullPath: '/contrats/mes-contrats'
      preLoaderRoute: typeof AuthenticatedContratsMesContratsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/depots/mes-produits': {
      id: '/_authenticated/depots/mes-produits'
      path: '/depots/mes-produits'
      fullPath: '/depots/mes-produits'
      preLoaderRoute: typeof AuthenticatedDepotsMesProduitsImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/depots/nouveau-produit': {
      id: '/_authenticated/depots/nouveau-produit'
      path: '/depots/nouveau-produit'
      fullPath: '/depots/nouveau-produit'
      preLoaderRoute: typeof AuthenticatedDepotsNouveauProduitImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/ventes/enchere-creee': {
      id: '/_authenticated/ventes/enchere-creee'
      path: '/ventes/enchere-creee'
      fullPath: '/ventes/enchere-creee'
      preLoaderRoute: typeof AuthenticatedVentesEnchereCreeeImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/ventes/mes-encheres': {
      id: '/_authenticated/ventes/mes-encheres'
      path: '/ventes/mes-encheres'
      fullPath: '/ventes/mes-encheres'
      preLoaderRoute: typeof AuthenticatedVentesMesEncheresImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/ventes/nouvelle-enchere': {
      id: '/_authenticated/ventes/nouvelle-enchere'
      path: '/ventes/nouvelle-enchere'
      fullPath: '/ventes/nouvelle-enchere'
      preLoaderRoute: typeof AuthenticatedVentesNouvelleEnchereImport
      parentRoute: typeof AuthenticatedImport
    }
  }
}

// Create and export the route tree

interface AuthenticatedRouteChildren {
  AuthenticatedProfilRoute: typeof AuthenticatedProfilRoute
  AuthenticatedAchatsMarcheRoute: typeof AuthenticatedAchatsMarcheRoute
  AuthenticatedAchatsMesEncheresRoute: typeof AuthenticatedAchatsMesEncheresRoute
  AuthenticatedContratsMesContratsRoute: typeof AuthenticatedContratsMesContratsRoute
  AuthenticatedDepotsMesProduitsRoute: typeof AuthenticatedDepotsMesProduitsRoute
  AuthenticatedDepotsNouveauProduitRoute: typeof AuthenticatedDepotsNouveauProduitRoute
  AuthenticatedVentesEnchereCreeeRoute: typeof AuthenticatedVentesEnchereCreeeRoute
  AuthenticatedVentesMesEncheresRoute: typeof AuthenticatedVentesMesEncheresRoute
  AuthenticatedVentesNouvelleEnchereRoute: typeof AuthenticatedVentesNouvelleEnchereRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfilRoute: AuthenticatedProfilRoute,
  AuthenticatedAchatsMarcheRoute: AuthenticatedAchatsMarcheRoute,
  AuthenticatedAchatsMesEncheresRoute: AuthenticatedAchatsMesEncheresRoute,
  AuthenticatedContratsMesContratsRoute: AuthenticatedContratsMesContratsRoute,
  AuthenticatedDepotsMesProduitsRoute: AuthenticatedDepotsMesProduitsRoute,
  AuthenticatedDepotsNouveauProduitRoute:
    AuthenticatedDepotsNouveauProduitRoute,
  AuthenticatedVentesEnchereCreeeRoute: AuthenticatedVentesEnchereCreeeRoute,
  AuthenticatedVentesMesEncheresRoute: AuthenticatedVentesMesEncheresRoute,
  AuthenticatedVentesNouvelleEnchereRoute:
    AuthenticatedVentesNouvelleEnchereRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren
)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCooperativesRoute: typeof AdminCooperativesRoute
  AdminGlobalSettingsRoute: typeof AdminGlobalSettingsRoute
  AdminMagasinRoute: typeof AdminMagasinRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCooperativesRoute: AdminCooperativesRoute,
  AdminGlobalSettingsRoute: AdminGlobalSettingsRoute,
  AdminMagasinRoute: AdminMagasinRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '': typeof AuthenticatedRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/inscription-succes': typeof InscriptionSuccesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/actualites/$newsId': typeof ActualitesNewsIdRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cooperatives': typeof AdminCooperativesRoute
  '/admin/global-settings': typeof AdminGlobalSettingsRoute
  '/admin/magasin': typeof AdminMagasinRoute
  '/admin/users': typeof AdminUsersRoute
  '/contact/merci': typeof ContactMerciRoute
  '/actualites': typeof ActualitesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/achats/marche': typeof AuthenticatedAchatsMarcheRoute
  '/achats/mes-encheres': typeof AuthenticatedAchatsMesEncheresRoute
  '/contrats/mes-contrats': typeof AuthenticatedContratsMesContratsRoute
  '/depots/mes-produits': typeof AuthenticatedDepotsMesProduitsRoute
  '/depots/nouveau-produit': typeof AuthenticatedDepotsNouveauProduitRoute
  '/ventes/enchere-creee': typeof AuthenticatedVentesEnchereCreeeRoute
  '/ventes/mes-encheres': typeof AuthenticatedVentesMesEncheresRoute
  '/ventes/nouvelle-enchere': typeof AuthenticatedVentesNouvelleEnchereRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '': typeof AuthenticatedRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/inscription-succes': typeof InscriptionSuccesRoute
  '/profil': typeof AuthenticatedProfilRoute
  '/actualites/$newsId': typeof ActualitesNewsIdRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cooperatives': typeof AdminCooperativesRoute
  '/admin/global-settings': typeof AdminGlobalSettingsRoute
  '/admin/magasin': typeof AdminMagasinRoute
  '/admin/users': typeof AdminUsersRoute
  '/contact/merci': typeof ContactMerciRoute
  '/actualites': typeof ActualitesIndexRoute
  '/admin': typeof AdminIndexRoute
  '/contact': typeof ContactIndexRoute
  '/achats/marche': typeof AuthenticatedAchatsMarcheRoute
  '/achats/mes-encheres': typeof AuthenticatedAchatsMesEncheresRoute
  '/contrats/mes-contrats': typeof AuthenticatedContratsMesContratsRoute
  '/depots/mes-produits': typeof AuthenticatedDepotsMesProduitsRoute
  '/depots/nouveau-produit': typeof AuthenticatedDepotsNouveauProduitRoute
  '/ventes/enchere-creee': typeof AuthenticatedVentesEnchereCreeeRoute
  '/ventes/mes-encheres': typeof AuthenticatedVentesMesEncheresRoute
  '/ventes/nouvelle-enchere': typeof AuthenticatedVentesNouvelleEnchereRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/a-propos': typeof AProposRoute
  '/admin': typeof AdminRouteWithChildren
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/inscription-succes': typeof InscriptionSuccesRoute
  '/_authenticated/profil': typeof AuthenticatedProfilRoute
  '/actualites/$newsId': typeof ActualitesNewsIdRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/cooperatives': typeof AdminCooperativesRoute
  '/admin/global-settings': typeof AdminGlobalSettingsRoute
  '/admin/magasin': typeof AdminMagasinRoute
  '/admin/users': typeof AdminUsersRoute
  '/contact/merci': typeof ContactMerciRoute
  '/actualites/': typeof ActualitesIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/contact/': typeof ContactIndexRoute
  '/_authenticated/achats/marche': typeof AuthenticatedAchatsMarcheRoute
  '/_authenticated/achats/mes-encheres': typeof AuthenticatedAchatsMesEncheresRoute
  '/_authenticated/contrats/mes-contrats': typeof AuthenticatedContratsMesContratsRoute
  '/_authenticated/depots/mes-produits': typeof AuthenticatedDepotsMesProduitsRoute
  '/_authenticated/depots/nouveau-produit': typeof AuthenticatedDepotsNouveauProduitRoute
  '/_authenticated/ventes/enchere-creee': typeof AuthenticatedVentesEnchereCreeeRoute
  '/_authenticated/ventes/mes-encheres': typeof AuthenticatedVentesMesEncheresRoute
  '/_authenticated/ventes/nouvelle-enchere': typeof AuthenticatedVentesNouvelleEnchereRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | ''
    | '/a-propos'
    | '/admin'
    | '/connexion'
    | '/inscription'
    | '/inscription-succes'
    | '/profil'
    | '/actualites/$newsId'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/cooperatives'
    | '/admin/global-settings'
    | '/admin/magasin'
    | '/admin/users'
    | '/contact/merci'
    | '/actualites'
    | '/admin/'
    | '/contact'
    | '/achats/marche'
    | '/achats/mes-encheres'
    | '/contrats/mes-contrats'
    | '/depots/mes-produits'
    | '/depots/nouveau-produit'
    | '/ventes/enchere-creee'
    | '/ventes/mes-encheres'
    | '/ventes/nouvelle-enchere'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | ''
    | '/a-propos'
    | '/connexion'
    | '/inscription'
    | '/inscription-succes'
    | '/profil'
    | '/actualites/$newsId'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/cooperatives'
    | '/admin/global-settings'
    | '/admin/magasin'
    | '/admin/users'
    | '/contact/merci'
    | '/actualites'
    | '/admin'
    | '/contact'
    | '/achats/marche'
    | '/achats/mes-encheres'
    | '/contrats/mes-contrats'
    | '/depots/mes-produits'
    | '/depots/nouveau-produit'
    | '/ventes/enchere-creee'
    | '/ventes/mes-encheres'
    | '/ventes/nouvelle-enchere'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/_authenticated'
    | '/a-propos'
    | '/admin'
    | '/connexion'
    | '/inscription'
    | '/inscription-succes'
    | '/_authenticated/profil'
    | '/actualites/$newsId'
    | '/admin/analytics'
    | '/admin/blog'
    | '/admin/cooperatives'
    | '/admin/global-settings'
    | '/admin/magasin'
    | '/admin/users'
    | '/contact/merci'
    | '/actualites/'
    | '/admin/'
    | '/contact/'
    | '/_authenticated/achats/marche'
    | '/_authenticated/achats/mes-encheres'
    | '/_authenticated/contrats/mes-contrats'
    | '/_authenticated/depots/mes-produits'
    | '/_authenticated/depots/nouveau-produit'
    | '/_authenticated/ventes/enchere-creee'
    | '/_authenticated/ventes/mes-encheres'
    | '/_authenticated/ventes/nouvelle-enchere'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AProposRoute: typeof AProposRoute
  AdminRoute: typeof AdminRouteWithChildren
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  InscriptionSuccesRoute: typeof InscriptionSuccesRoute
  ActualitesNewsIdRoute: typeof ActualitesNewsIdRoute
  ContactMerciRoute: typeof ContactMerciRoute
  ActualitesIndexRoute: typeof ActualitesIndexRoute
  ContactIndexRoute: typeof ContactIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AProposRoute: AProposRoute,
  AdminRoute: AdminRouteWithChildren,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  InscriptionSuccesRoute: InscriptionSuccesRoute,
  ActualitesNewsIdRoute: ActualitesNewsIdRoute,
  ContactMerciRoute: ContactMerciRoute,
  ActualitesIndexRoute: ActualitesIndexRoute,
  ContactIndexRoute: ContactIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/403",
        "/_authenticated",
        "/a-propos",
        "/admin",
        "/connexion",
        "/inscription",
        "/inscription-succes",
        "/actualites/$newsId",
        "/contact/merci",
        "/actualites/",
        "/contact/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/403": {
      "filePath": "403.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/profil",
        "/_authenticated/achats/marche",
        "/_authenticated/achats/mes-encheres",
        "/_authenticated/contrats/mes-contrats",
        "/_authenticated/depots/mes-produits",
        "/_authenticated/depots/nouveau-produit",
        "/_authenticated/ventes/enchere-creee",
        "/_authenticated/ventes/mes-encheres",
        "/_authenticated/ventes/nouvelle-enchere"
      ]
    },
    "/a-propos": {
      "filePath": "a-propos.tsx"
    },
    "/admin": {
      "filePath": "admin.tsx",
      "children": [
        "/admin/analytics",
        "/admin/blog",
        "/admin/cooperatives",
        "/admin/global-settings",
        "/admin/magasin",
        "/admin/users",
        "/admin/"
      ]
    },
    "/connexion": {
      "filePath": "connexion.tsx"
    },
    "/inscription": {
      "filePath": "inscription.tsx"
    },
    "/inscription-succes": {
      "filePath": "inscription-succes.tsx"
    },
    "/_authenticated/profil": {
      "filePath": "_authenticated/profil.tsx",
      "parent": "/_authenticated"
    },
    "/actualites/$newsId": {
      "filePath": "actualites/$newsId.tsx"
    },
    "/admin/analytics": {
      "filePath": "admin/analytics.tsx",
      "parent": "/admin"
    },
    "/admin/blog": {
      "filePath": "admin/blog.tsx",
      "parent": "/admin"
    },
    "/admin/cooperatives": {
      "filePath": "admin/cooperatives.tsx",
      "parent": "/admin"
    },
    "/admin/global-settings": {
      "filePath": "admin/global-settings.tsx",
      "parent": "/admin"
    },
    "/admin/magasin": {
      "filePath": "admin/magasin.tsx",
      "parent": "/admin"
    },
    "/admin/users": {
      "filePath": "admin/users.tsx",
      "parent": "/admin"
    },
    "/contact/merci": {
      "filePath": "contact/merci.tsx"
    },
    "/actualites/": {
      "filePath": "actualites/index.tsx"
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/contact/": {
      "filePath": "contact/index.tsx"
    },
    "/_authenticated/achats/marche": {
      "filePath": "_authenticated/achats/marche.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/achats/mes-encheres": {
      "filePath": "_authenticated/achats/mes-encheres.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/contrats/mes-contrats": {
      "filePath": "_authenticated/contrats/mes-contrats.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/depots/mes-produits": {
      "filePath": "_authenticated/depots/mes-produits.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/depots/nouveau-produit": {
      "filePath": "_authenticated/depots/nouveau-produit.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/ventes/enchere-creee": {
      "filePath": "_authenticated/ventes/enchere-creee.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/ventes/mes-encheres": {
      "filePath": "_authenticated/ventes/mes-encheres.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/ventes/nouvelle-enchere": {
      "filePath": "_authenticated/ventes/nouvelle-enchere.tsx",
      "parent": "/_authenticated"
    }
  }
}
ROUTE_MANIFEST_END */
