services:
  db:
    image: postgis/postgis:17-3.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: S5mhPe(+6CvWZbhj
      POSTGRES_DB: anacarde
      POSTGRES_USER: anacarde
    ports:
      - "5432:5432"
    volumes:
      - /opt/docker-data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U anacarde -d anacarde"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports: 
      - "8081:80"
    depends_on:
      db: 
        condition: service_healthy
    volumes: 
      - ./api/servers.json:/pgadmin4/servers.json

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /opt/docker-data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    image: ibonmr/anacarde-api:latest
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/anacarde
      SPRING_DATASOURCE_USERNAME: anacarde
      SPRING_DATASOURCE_PASSWORD: S5mhPe(+6CvWZbhj
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8080:8080" 
    volumes:
      - /opt/docker-data/uploads:/opt/anacarde/uploads

  client:
    image: ibonmr/anacarde-client:latest
    depends_on:
      - api 
    ports:
      - "3000:80"
