services:
  db:
    image: postgis/postgis:17-3.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: S5mhPe(+6CvWZbhj
      POSTGRES_DB: anacarde
      POSTGRES_USER: anacarde
    ports:
      - "5432:5432"
    volumes:
      - anacarde-database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h 127.0.0.1 -p 5432 -U anacarde -d anacarde"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 120s

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports: 
      - "8081:80"
    depends_on:
      db: 
        condition: service_healthy
    volumes: 
      - ./api/servers.json:/pgadmin4/servers.json

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports: 
      - "1025:1025" 
      - "8025:8025" 
    volumes: 
      - mailpit-data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8025 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /opt/docker-data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/anacarde
      SPRING_DATASOURCE_USERNAME: anacarde
      SPRING_DATASOURCE_PASSWORD: S5mhPe(+6CvWZbhj
      SPRING_MAIL_HOST: mailpit
      SPRING_MAIL_PORT: 1025
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      APP_INIT_TESTDATA: false
    ports:
      - "8080:8080" 
    volumes:
      - uploads:/opt/anacarde/uploads
    restart: on-failure

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - api 
    ports:
      - "3000:443" # Map host port 3000 to container port 443 (HTTPS)
      # You might want to keep HTTP available for local testing or let Nginx redirect
      # - "8088:80" # Example: map host port 8088 to container port 80 (HTTP)
    environment:
      VITE_API_BASE_URL: https://localhost:8080
      VITE_GOOGLE_CLIENT_ID: 996283363243-6q54sekeaff54ft34tjmbjkfqo8k9dmg.apps.googleusercontent.com

volumes:
  anacarde-database:
  mailpit-data:
  uploads: