// This file is auto-generated by @hey-api/openapi-ts

import { z } from 'zod'

export const zRoleDto = z.object({
  id: z.number().int().readonly().optional(),
  name: z.string().min(1),
})

export const zLanguageDto = z.object({
  id: z.number().int().readonly().optional(),
  name: z.string().min(1),
})

export const zUserDetailDto = z.object({
  id: z.number().int().readonly().optional(),
  firstName: z.string().min(1),
  lastName: z.string().min(1),
  email: z.string().min(1),
  registrationDate: z.iso.datetime().readonly().optional(),
  validationDate: z.iso.datetime().readonly().optional(),
  enabled: z.boolean().optional(),
  address: z.string().optional(),
  phone: z
    .string()
    .regex(/^(?:\+229)?(?:01[2-9]\d{7}|[2-9]\d{7})$/)
    .optional(),
  password: z.string().optional(),
  roles: z.array(zRoleDto).readonly().optional(),
  language: zLanguageDto,
  type: z.enum([
    'admin',
    'producer',
    'transformer',
    'quality_inspector',
    'exporter',
    'carrier',
  ]),
})
