get:
  tags:
    - products
  summary: Get a product by ID
  description: Return a single product
  operationId: getProduct
  parameters:
    - name: productId
      in: path
      description: ID of product to return
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '200':
      description: Request successful
      content:
        application/json:
          schema:
            $ref: '../components/schemas/Product.yaml'

    '400':
      description: Bad request
      content: 
        application/json:
          schema:
            $ref: ../components/schemas/ApiError.yaml

    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApiError.yaml

    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApiError.yaml

put:
  tags:
    - products
  summary: Update a product
  description: ''
  operationId: updateProduct
  parameters:
    - name: productId
      in: path
      description: ID of product to update
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '200':
      description: Request successful
      content:
        application/json:
          schema:
            $ref: '../components/schemas/Product.yaml'
    '400':
      description: Bad request
      content: 
        application/json:
          schema:
            $ref: ../components/schemas/ApiError.yaml

    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApiError.yaml

    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApiError.yaml

delete:
  tags:
    - products
  summary: Delete a product
  description: ''
  operationId: deleteProduct
  parameters:
    - name: productId
      in: path
      description: Product id to delete
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '200':
      description: Request successful
      content:
        application/json:
          schema:
            $ref: '../components/schemas/Product.yaml'
    '400':
      description: Bad request
      content: 
        application/json:
          schema:
            $ref: ../components/schemas/ApiError.yaml

    '401':
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApiError.yaml

    '403':
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: ../components/schemas/ApiError.yaml
