get:
  tags:
    - products
  summary: Find a product by ID
  description: Return a single product
  operationId: getProduct
  parameters:
    - name: productId
      in: path
      description: ID of product to return
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '200':
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: ..\components\schemas\Product.yaml
    '400':
      description: Invalid ID supplied
    '404':
      description: User not found

put:
  tags:
    - products
  summary: Update a product
  description: ''
  operationId: updateProduct
  parameters:
    - name: productId
      in: path
      description: ID of product to update
      required: true
      schema:
        type: integer
        format: int64
    - name: name
      in: query
      description: Name of product to update
      schema:
        type: string
  responses:
    '405':
      description: Invalid input

delete:
  tags:
    - products
  summary: Delete a product
  description: ''
  operationId: deleteProduct
  parameters:
    - name: productId
      in: path
      description: Product id to delete
      required: true
      schema:
        type: integer
        format: int64
  responses:
    '400':
      description: Invalid product value
