services:
  db:
    image: postgis/postgis:17-3.5-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: S5mhPe(+6CvWZbhj
      POSTGRES_DB: anacarde
      POSTGRES_USER: anacarde
    ports:
      - "5432:5432"
    volumes:
      - anacarde-database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d restapi"]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8081:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./servers.json:/pgadmin4/servers.json
      - ./pgadmin_data:/var/lib/pgadmin

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - mailpit-data:/data
     # - ./data/mailpit:/data
    ports:
      - "1025:1025"   # SMTP pour Spring Boot
      - "8025:8025"   # UI Web MailPit
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8025 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  anacarde-database:
  mailpit-data:
