name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: temurin

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('api/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven

      - name: Check code format with Spotless
        working-directory: ./api
        run: mvn spotless:check

      - name: Build project and run tests
        working-directory: ./api
        run: mvn --batch-mode --update-snapshots verify

      - name: Generate JaCoCo Badge
        if: github.ref == 'refs/heads/main'
        uses: cicirello/jacoco-badge-generator@v2
        id: jacoco

      - name: Log coverage percentages to workflow output
        if: github.ref == 'refs/heads/main'
        run: |
          echo "coverage = ${{ steps.jacoco.outputs.coverage }}"
          echo "branches = ${{ steps.jacoco.outputs.branches }}"

      - name: Commit and push the badge (if it changed)
        if: github.ref == 'refs/heads/main'
        uses: EndBug/add-and-commit@v7
        with:
          default_author: github_actions
          message: 'Update Jacoco badge'
          add: '*.svg'

      - name: Upload JaCoCo coverage report
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: api/target/site/jacoco/

      - name: Generate Documentation with Doxygen
        working-directory: ./api
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz
          doxygen Doxyfile

      - name: Upload Doxygen Documentation
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-doc
          path: api/docs/html

  qodana_scan:
    runs-on: ubuntu-latest
    needs: build-and-test
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Qodana JVM Community
        uses: docker://jetbrains/qodana-jvm-community:2024.3
        with:
          args: --project-dir /github/workspace/api --save-report /github/workspace/qodana-results

      - name: Fail if critical issues are detected
        run: |
          if grep -qi "Critical" /github/workspace/qodana-results/report.txt; then
            echo "Critical issues detected, failing the build."
            exit 1
          fi
