name: Code Quality

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  code_quality:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 

      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: --fail-threshold,0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
